
# Consistency and positivity

## Asking good causal questions

> Sep 17. [**Slides.**]() After class, read [Hernán and Robins 2020](https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/) Chapter 3.4-3.5. Optionally, read [Hernán 2016](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5207342/).

What makes causal inference with observational data so challenging? Why is making treatment precise so important? These are the topics we'll discuss in this lecture!


## Lab: Exchangeability and Consistency Review

> Sep 18 [**Slides.**]()

You will go through an activity to really hone in on the concepts of exchangeability and consistency.

## Asking good causal questions

> Sep 19. [**Slides.**]() After class, read [Hernán and Robins 2020](https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/) Chapter 3.3 & 3.6. Optionally, read [Sobel 2007](https://www.tandfonline.com/doi/abs/10.1198/016214506000000636).

Good causal questions are structured so that credibility is strong for two key assumptions: positivity and consistency.

1. **Positivity.** Every population subgroup receives every treatment value with non-zero probability
2. **Consistency.** Potential outcomes $Y^A$ are well-defined and linked to observable data

