
# Regression discontinuity


## Introduction

> Oct 29. [**Slides.**](assets/slides/rdd_intro.pdf) After class, read [Huntington Klein 2021](https://theeffectbook.net/ch-RegressionDiscontinuity.html) Chapter 20, sections 20.1 and 20.3.4. Slides with annotations from lecture: [**Annotated Slides.**](assets/slides/rdd_intro_annotated.pdf)

In some settings, a treatment is assigned based solely off the value of a continuous variable. In these situations, we can identify a local ATE without many additional assumptions. Today will introduce how this works using regression discontinuity designs. 

## Lab: Regression Discontinuity - Bandwidth and Examples

> Oct 30 After lab, read [Huntington Klein 2021](https://theeffectbook.net/ch-RegressionDiscontinuity.html) Chapter 20, section 20.2.1.
[**Slides**]() Download today's [**.Rmd document here**]().

We'll discuss a bandwidth selection and triangular weighting. We'll also apply regression discontinuity to a concrete example and give you a chance to try it out for yourself.

## Discussion

> Oct 31. [**Slides.**]() After class, read [Huntington Klein 2021](https://theeffectbook.net/ch-RegressionDiscontinuity.html) Chapter 20, sections 20.2.2. through 20.3.1.

We'll continue our discussion of regression discontinuity designs by discussing fuzzy RDD and validation checks for RDD.