# Problem Set 3. DAGs. {-}

Relevant material will be covered by **Sep 25**. Problem set is due **Oct 8**.

To complete the problem set, [**Download the .Rmd**](assets/psets/pset3_download_fa25.Rmd) and complete the homework. Omit your name so we can have anonymous peer feedback. Compile to a PDF and submit the PDF on Canvas.



## 1. True or False {-}

For 1.1--1.5, answer True or False: The $Z$ nodes (i.e., either $Z$ itself or the set $\{Z_1, Z_2, \ldots \}$) form a sufficient adjustment set to identify the causal effect of $A$ on $Y$. Explain your answer in one sentence. If False, state the backdoor path that is unblocked conditional on $Z$.


\vspace{2em}

<script type="text/tikz">
\begin{tikzpicture}
    \node[anchor = north west] at (-1.5,2) {1.1.  (4 points)};
    \node (x) at (-1,0) {$Z$};
    \node (a) at (0,0) {$A$};
    \node (y) at (1,0) {$Y$};
    \draw[->, thick] (a) -- (y);
    \draw[->, thick] (x) -- (a);
    \draw[->, thick] (x) to[bend right] (y);
    \node (u1) at (-.5,1) {$U$};
    \draw[->, thick] (u1) -- (x);
    \draw[->, thick] (u1) -- (a);
    \node at (0,-1.2) {};
\end{tikzpicture}
\begin{tikzpicture}
    \node[anchor = north west] at (-1.5,2) {1.2. (4 points)};
    \node (x) at (-1,0) {$Z$};
    \node (a) at (0,0) {$A$};
    \node (y) at (1,0) {$Y$};
    \draw[->, thick] (a) -- (y);
    \draw[->, thick] (x) -- (a);
    \draw[->, thick] (x) to[bend right] (y);
    \node (u1) at (-.5,1) {$U_2$};
    \draw[->, thick] (u1) -- (x);
    \draw[->, thick] (u1) -- (a);
    \node (u2) at (-1,-1) {$U_1$};
    \draw[->, thick] (u2) -- (x);
    \draw[->, thick] (u2) to[bend right] (y);
    \node at (0,-1.2) {};
\end{tikzpicture}
\begin{tikzpicture}
    \node[anchor = north west] at (-1.5,2) {1.3.  (4 points)};
    \node (z1) at (-1,0) {$Z_1$};
    \node (z2) at (0,1) {$Z_2$};
    \node (u) at (1,1) {$U$};
    \node (a) at (0,0) {$A$};
    \node (y) at (1,0) {$Y$};
    \draw[->, thick] (a) -- (y);
    \draw[->, thick] (z1) -- (a);
    \draw[->, thick] (z2) -- (y);
    \draw[->, thick] (z2) -- (a);
    \draw[->, thick] (u) -- (y);
    \draw[->, thick] (u) -- (z2);
    \draw[->, thick] (x) to[bend right] (y);
    \node at (0,-1.2) {};
\end{tikzpicture}
\begin{tikzpicture}
    \node[anchor = north west] at (-1.5,2) {1.4. (4 points)};
    \node (z1) at (-1,0) {$Z_1$};
    \node (z2) at (.5,-1) {$Z_2$};
    \node (a) at (0,0) {$A$};
    \node (y) at (1,0) {$Y$};
    \draw[->, thick] (a) -- (y);
    \draw[->, thick] (z1) -- (a);
    \draw[->, thick] (x) to[bend left] (y);
    \draw[->, thick] (a) -- (z2);
    \draw[->, thick] (y) -- (z2);
    \node at (0,-1.2) {};
\end{tikzpicture}
\begin{tikzpicture}
    \node[anchor = north west] at (-1.5,2) {1.5.  (4 points)};
    \node (x) at (-1,0) {$Z$};
    \node (a) at (0,0) {$A$};
    \node (y) at (1,0) {$Y$};
    \draw[->, thick] (a) -- (y);
    \draw[->, thick] (x) -- (a);
    \draw[->, thick] (x) to[bend right] (y);
    \node (u1) at (.5,1) {$U$};
    \draw[->, thick] (u1) -- (a);
    \draw[->, thick] (u1) -- (y);
    \node at (0,-1.2) {};
\end{tikzpicture}
</script>


### 1.1 (2 points) {-}
**Answer.** Your answer here

### 1.2 (2 points) {-}
**Answer.** Your answer here

### 1.3 (2 points) {-}
**Answer.** Your answer here

### 1.4 (2 points) {-}
**Answer.** Your answer here

### 1.5 (2 points) {-}
**Answer.** Your answer here



## 2. Which DAG is ''Correct''? {-}
Suppose you and your classmate are interested in estimating the causal effect of being an New York resident on admission to Cornell as an undergraduate. Your classmate states a causal DAG which they believe describes the causal system. The included variables are:

* Residency: This is the treatment and is either NY or non-NY
* Admission: This is the outcome and is either Yes or No
* Family SES: The socioeconomic level of the applicant's family
* SAT scores: The applicant's SAT score
* Legacy: Whether or not an applicant has family members who are Cornell alumni


<script type="text/tikz">
\begin{tikzpicture}[
  node distance=15mm and 25mm,
  every node/.style={font=\sffamily, align=center},
  box/.style={draw, rounded corners, minimum width=25mm, minimum height=8mm},
  arr/.style={-{Latex[length=3mm]}, line width=0.8pt}
]


\node[box] (SES) {Family SES};
\node[box, below=20mm of SES] (Legacy) {Legacy};
\node[box, right=10mm of SES] (Residency) {A: Residency};
\node[box, above=of Residency] (SAT) {SAT scores};

\node[box, right=20mm of Residency] (Admission) {Y: Admission};


\draw[arr] (Residency) -- (Admission);
\draw[arr] (SES) -- (Residency);
\draw[arr] (SES) -- (SAT);
\draw[arr, bend right=40] (SES) to (Admission);
\draw[arr] (SAT) -- (Admission);
\draw[arr] (Legacy) -- (Admission);
\draw[arr] (Legacy) -- (SES);

\end{tikzpicture}
</script>


### 2.1 (5 pts) {-}
Write out the notation for the potential outcomes (for a generic individual $i$) using the notation from class.

**Answer.**


### 2.1 (8 pts) {-}
In the causal diagram above list all the paths from Residency to Admission and state whether they are causal paths or not. For each of the paths that contains more than just the treatment and outcome, indicate whether each node on that path is a collider or non-collider. There should be 4 paths total.

**Answer.** 

* Path 1:
* Path 2:
* Path 3:
* Path 4:

### 2.2 (8 pts) {-}
For each path above, determine if the path is open or blocked when conditioning on ''Family SES.'' Explain why for each path. 

**Answer.** 

* Path 1: 
* Path 2:
* Path 3:
* Path 4:

### 2.3 (5 pts) {-}
Suppose your classmate uses standardization to estimate a causal effect by conditioning on ''Family SES.'' **Assuming** the graph is correct, does conditional exchangeability hold? Why or why not?  

**Answer**

### 2.4 (8 pts) {-}
Since individual admissions data are not publicly available, you recall that your classmate gathered the data by first collecting contact information from high school students who visited Cornell. After admissions decisions were released, your classmate sent these individuals a email with a link to the survey. Thus, you add the following variables to the graph

* Visit: Whether or not a student visits Cornell
* Respond: Whether or not a student responded to the survey

Students who live in NY are more likely to visit since they are closer. Students who visit are more likely to get a link to the survey so that they can respond. Also, students who get admitted are more likely to respond (or said another way, students who did not get admitted are less likely to respond). Thus, you think this is a more accurate causal graph. 

<script type="text/tikz">
\begin{tikzpicture}[
  node distance=15mm and 25mm,
  every node/.style={font=\sffamily, align=center},
  box/.style={draw, rounded corners, minimum width=25mm, minimum height=8mm},
  arr/.style={-{Latex[length=3mm]}, line width=0.8pt}
]


\node[box] (SES) {Family SES};
\node[box, below=20mm of SES] (Legacy) {Legacy};
\node[box, above=20mm of SES] (PE) {Parents Edu};
\node[box, right=10mm of SES] (Residency) {A: Residency};
\node[box, above=of Residency] (SAT) {SAT scores};
\node[box, right=10mm of Legacy] (Visit) {Visit};
\node[box, right=20mm of Visit] (Respond) {Respond};


% Right column (outcome)
\node[box, right=20mm of Residency] (Admission) {Y: Admission};

% Edges
\draw[arr] (Residency) -- (Admission);
\draw[arr] (SES) -- (Residency);
\draw[arr] (SES) -- (SAT);
\draw[arr, bend right=40] (SES) to (Admission);
\draw[arr] (PE) -- (SAT);
\draw[arr] (SAT) -- (Admission);
\draw[arr] (Legacy) -- (Admission);
\draw[arr] (Legacy) -- (Admission);
\draw[arr] (Residency) -- (Visit);
\draw[arr] (Visit) -- (Respond);
\draw[arr] (Admission) -- (Respond);


\end{tikzpicture}
</script>

Since you only have data on students who responded, the analysis your classmate conducted implicitly conditions on ''Respond.'' In this case, is the causal estimate your classmate estimated still reliable? Why or why not?

**Answer.** Your answer here

