
# (PART) Assignments {-}

# Due dates {-}

We'll post due dates here throughout the semester. 

## Upcoming {-}

- Pset 3 **Peer Reviews**: Due Thursday, October 24th at 11:59pm (released Oct 16)

- Pset 4: Due Friday, October 25th at 11:59pm (released Oct 17)

## Future {-}

*Important: These dates are tentative, meaning they may change. We will not make any of these due sooner, meaning they will be due at the date listed or possibly later. We have not included dates for all assignments!*

- **Project** Task 3: Not yet assigned

- Pset 4 **Peer Reviews**: Due Friday, November 1st at 11:59pm (released Oct 28)

- Pset 5: Due Thursday, November 7th at 11:59pm (released Oct 31)

## Past {-}

- **Project** Task 2: Due Thursday, October 17th at 11:59pm via Canvas

- Pset 1: Due Tuesday, September 10th at 5pm 

- Pset 1 **Peer Reviews**: Due Tuesday, September 17th at 5pm 

- Pset 2: Due Tuesday, September 24th at 11:59pm 

- Pset 2 **Peer Reviews**: Due Tuesday, October 1st at 11:59pm 

- **Project** Task 1: Due Thursday, October 3rd at 11:59pm

- Pset 3: Due Friday, October 11th at 11:59pm via Canvas