---
output: pdf_document
---

# Course Project: Task 2  
Omit your name so we can have anonymous peer feedback. Compile to a PDF and submit the PDF on Canvas.

Take a look at the [Task 2 details](https://causal3900.github.io/assets/psets/project/task2.pdf) and fill out the Action Items listed out below.

# Action Items

Copy and paste the description of your causal question from Task 1 so the grader has some context for your problem.

**Answer.** Your answer here    

## (2 pts) Write out the names of the treatment variable $A$ and the outcome variable $Y$ you are considering. 

**Answer.** Your answer here


## (3 pts) List out 4-6 factors that are particularly relevant for your causal question. These might be variables which either

* Cause (either directly or through other factors) both your treatment variable and your potential outcomes
* Are caused by both the treatment and the outcome

Note, it would be good---but not necessary---if these variables are also included in the data set you considered in Task 1.
    
**Answer.** Your answer here

## (10 points) Draw a DAG that includes your treatment variable, outcome variable, and the factors you listed in the previous part. If you use letters for variables names, make sure you explain what the letter stands for.

**Answer.** Your answer here


## (5 points) In a few sentences, explain your DAG: tell us in words what is meant by each edge in your DAG.

**Answer.** Your answer here

## (5 points) Assuming your DAG is true, list one sufficient adjustment set to identify the causal effect of the treatment on the outcome. If a sufficient adjustment set does not exist, add additional variables to your DAG so that one does exist. 

**Answer.** Your answer here
