---
output: pdf_document
---

# Problem Set 1. Definitions 

Relevant material will be covered by **Aug 28**. Problem set is due **Sept 9** at 11:59pm.

Welcome to the first problem set! This homework will practice conceptual and notation ideas for descriptive and causal inference.

To complete the problem set, [**Download the .Rmd**](assets/psets/pset1_download.Rmd) and complete the homework. Omit your name so we can have anonymous peer feedback. Compile to a PDF and submit the PDF on Canvas.

## 1. Practice with potential outcomes {-}

Popeye says that eating spinach caused him to grow strong muscles. He claims that if he had not eaten spinach, he would not have grown strong muscles.  

### 1.1 (7 points) {-}

In Popeye's claim, what is the treatment? You can either describe the treatment variable or explicitly write out the two options the treatment variable can take.

**Answer.** Your answer here

### 1.2 (7 points) {-}

Using the mathematical notation we discussed in class, define the two potential outcomes to which Popeye is referring

**Answer.** Your answer here

### 1.3 (7 points) {-}

In a sentence or two, say how the Fundamental Problem of Causal Inference applies to Popeye's claim.

**Answer.** Your answer here

### 1.4 (7 points) {-}

Using conditional expectations or probabilities, write the following in math: the probability of having strong muscles is higher among individuals who eat spinach than among individuals who do not eat spinach.

**Answer.** Your answer here

### 1.5 (7 points) {-}

Give one reason why the average causal effect of eating spinach (the quantity from 1.2, averaged over all individuals) might be different from the average descriptive difference (from 1.4) of having strong muscles.

**Answer.** Your answer here


## 2. Taking 3900 {-}

You are wondering if taking STSCI 3900 will help you get a higher paying job. For each claim below, tell us whether the claim is causal or descriptive.

### 2.1 (5 points) {-}

Last year, there was a survey of all Cornell students who have graduated in the past two years. The students who did take 3900 reported an average salary of 85,000 dollars and the students who did not take 3900 reported an average salary of 78,000 dollars. 

**Answer.** Your answer here

### 2.2 (5 points) {-}

A student who did not take the course took a job after graduation that paid 80,000. Had this student taken the course, they would have taken a job that paid 85,000. 

**Answer.** Your answer here

### 2.3 (5 points) {-}

Among students who have an on-campus job and took the course, the average wage was 18.50/hr the semester before they took the course and the average wage the semester after taking the course was 21.25.  

**Answer.** Your answer here

### 2.4 (5 points) {-}

Students who took the course applied for twice as many jobs after graduation compared to students who did not take the course.  

**Answer.** Your answer here


## Session info

The chunk below will record information about your R session, which is useful for debugging issues in homework assignments that contain code.

```{r}
sessionInfo()
```